### ISSUE TITLE
Feature request: add option to include "defer" on any <script> tag added by the plugin

### ISSUE THREAD

**Issue by robmadole** [FortAwesome/wordpress-fontawesome#126]
We've had some customers that run a performance auditing tool (similar to Lighthouse perhaps?) that reports the <script> tags that the plugin adds are "blocking". Now while this is technically true it doesn't paint the whole picture.

The script that loads a Kit is small and generally pretty fast. But it **is** blocking. Once it finishes loading the rest of the Font Awesome assets are loaded asynchronously and do not block anything.

I'm not sure if we need this in other areas or not. This would probably also be beneficial for using the Pro CDN.

Proposed solution: add an option to add`defer` to the `<script>` tags.

**Comment by mlwilkerson** [comment]
@robmadole do you think `defer` should be the default?

If so, I wonder whether making it the default would need to wait until a major version increment. Not sure what functional difference it will make--since this is mostly about linting for a performance analysis tool.

Regardless, do you have any further suggestions about how might we add that option? One approach is to make it an option just like the others, configurable in the admin settings page. Another approach is to add a filter which would require advanced users to add a line of PHP code to a `functions.php` file (or equivalent) that would enable this feature.

Also, in my understanding of your proposal, the value of that option would apply to any <script> tags added by the plugin. So, not just the kit loader script, but also the `all.js` script (for example), if the plugin is configured to use CDN. Is that what you had in mind?

**Comment by mlwilkerson** [comment]
[Here's a WordPress support forum topic](https://wordpress.org/support/topic/css-urls-block-rendering/#post-15902664) related to this request.
