### ISSUE TITLE
Getting it to work.

### ISSUE THREAD

**Issue by paaljoachim** [FortAwesome/wordpress-fontawesome#166]
Hey 

I made this issue: Using Font Awesome with WordPress
https://github.com/FortAwesome/Font-Awesome/issues/18819

I am working on updating older WordPress tutorials that use Font Awesome. At the moment the old code is not working, so that I am working on figuring out the correct approach these days.

**Comment by mlwilkerson** [comment]
Hi @paaljoachim, I responded over on that [other issue](https://github.com/FortAwesome/Font-Awesome/issues/18819#issuecomment-1068352002). Since this repo is for the Font Awesome official WordPress plugin, and it sounds like you're asking about tutorial content for setting up FA on WordPress _without_ this plugin, I'll close this issue here. But I'm glad to continue the conversation about how you might update those tutorials to reflect FA6 usage patterns.

**Comment by paaljoachim** [comment]
Thanks Mike!
