### ISSUE TITLE
Error in a third-party's library takes down the hole website

### ISSUE THREAD

**Issue by ivansainz** [FortAwesome/wordpress-fontawesome#23]
I installed this **Font Awesome Official WordPress Plugin** and keep getting this error that doesn't let me access neither the website nor the administration panel.
If I delete the plugin directory (/wp-content/plugins/font-awesome-official) then I can access again to both the website and the administration panel.
Sometimes it works, sometimes it doesn't. I don't know what is the cause.

![image](https://user-images.githubusercontent.com/37206635/49451362-52940480-f7df-11e8-9528-b53218b43011.png)

Thanks in advance.

**Comment by mlwilkerson** [comment]
Hi @ivansainz. First of all, _thank you_ for giving this plugin a try and reporting feedback! Very helpful. It's still in a private beta state, and I'm quickly moving toward another release. So there have been _major_ changes on `master` since the `0.1.0` prototype release. In fact, just this morning, I merged a PR #22  that addresses error handling for that GuzzleHttp client.

So it would be helpful to know which version you had installed when you hit this error, and you might also try building and installing a version from the latest `master`. You could follow the "Cut a Release" instructions in [DEVELOPMENT.md](https://github.com/FortAwesome/wordpress-fontawesome/blob/master/DEVELOPMENT.md#to-cut-a-release) to build a new `font-awesome-official.zip` that you could try installing instead.

However, you might find that even after doing so, there's still a connection error (the `ConnectException` in your screenshot). The latest code on `master` will just will handle that exception gracefully instead of letting the plugin crash. This exception indicates that our [FontAwesome_Release_Provider](https://github.com/FortAwesome/wordpress-fontawesome/blob/8e34384bdf4e8cde21eda4e1645e8bc30a888556/includes/class-fontawesome-release-provider.php#L161) is not able to establish a connection with `fontawesome.com` to get the releases metadata. It shows that there's a network problem between your WordPress server and `fontawesome.com`. The only time I've gotten that error is when I'm doing local development and my development machine is not connected to the internet. So you might consider such network factors as well.

**Comment by ivansainz** [comment]
Hi @mlwilkerson,
I installed the last one release to date, that is 0.1.0. For now I just did it manually enqueueing the CSS file using the wp_enqueue_style() WordPress function, looking forward to your next release.
Thank you for your awesome work and support :wink: 👍
